
-- RELATORIO JOAO 

SELECT * FROM Pessoa WHERE NOME LIKE'%João%' ;

-- RELATORIO DE DIZIMOS DE MAIO

SELECT PESSOA.NOME, DIZIMO.VALOR, DIZIMO.DATA_PAGAMENTO
FROM PESSOA INNER JOIN DIZIMO
ON PESSOA.ID_PESSOA = DIZIMO.ID_PESSOA
WHERE MONTH (DATA_PAGAMENTO) = 05
GROUP BY NOME;

-- RELATORIO COM QUANTIDADE DE MEMBRO DE UMA IGREJA

SELECT IGREJA.NOME , SUM(IGREJA) AS QUANTIDADE_DE_MEMBROS
FROM PESSOA INNER JOIN IGREJA
ON PESSOA.IGREJA = IGREJA.ID_IGREJA
GROUP BY IGREJA;

-- RELATORIO DOS MEMBROS PRESBITEROS

SELECT NOME, NOME_CARGO AS CARGO
FROM PESSOA INNER JOIN PESSOA_CARGO
ON PESSOA.ID_PESSOA = PESSOA_CARGO.PESSOA
INNER JOIN CARGO
ON CARGO.ID_CARGO = PESSOA_CARGO.CARGO
HAVING (CARGO)  = "Presbitero";

-- RELATORIO COM AGENDAMENTO PASTORAL

SELECT PASTOR.NOME AS PASTOR, ACONSELHADA.NOME AS PESSOA_ACONSELHADA, DATA_ACONSELHAMENTO, HORA_INICIO, HORA_FIM, LOCAL_ACONSELHAMENTO
FROM PESSOA AS PASTOR
INNER JOIN AGENDAMENTO_PASTORAL AS AP
ON PASTOR.ID_PESSOA = AP.PESSOA_PASTOR
INNER JOIN PESSOA AS ACONSELHADA 
ON ACONSELHADA.ID_PESSOA = AP.PESSOA_ACONSELHADA;


-- PESSOAS QUE NUNCA DIZIMARAM

SELECT NOME AS MEMBROS_QUE_NUNCA_DIZIMARAM
FROM PESSOA LEFT OUTER JOIN DIZIMO
ON PESSOA.ID_PESSOA = DIZIMO.ID_PESSOA
WHERE DIZIMO.ID_PESSOA IS NULL;

-- PESSOAS QUE MAIS DIZIMOU NO ANO DE 2022

SELECT PESSOA.NOME, COUNT(DIZIMO.VALOR) AS QUANTIDADE_DE_DIZIMO FROM PESSOA INNER JOIN DIZIMO
ON PESSOA.ID_PESSOA = DIZIMO.ID_PESSOA
WHERE YEAR (DATA_PAGAMENTO) =  2022
GROUP BY NOME 
ORDER BY QUANTIDADE_DE_DIZIMO DESC;

-- PESSOAS QUE POSSUEM MAIS DE UM CARGO

SELECT NOME, COUNT(NOME_CARGO) AS QUANTIDADE_DE_CARGO
FROM PESSOA INNER JOIN PESSOA_CARGO
ON PESSOA.ID_PESSOA = PESSOA_CARGO.PESSOA
INNER JOIN CARGO
ON CARGO.ID_CARGO = PESSOA_CARGO.CARGO
GROUP BY NOME ORDER BY QUANTIDADE_DE_CARGO DESC;

-- PESSOAS QUE TEM O MAIOR DIZIMO DA HISTORIA DA IGREJA

SELECT PESSOA.NOME, DIZIMO.VALOR AS MAIOR_VALOR FROM PESSOA INNER JOIN DIZIMO
ON PESSOA.ID_PESSOA = DIZIMO.ID_PESSOA
WHERE YEAR (DATA_PAGAMENTO) =  2022
GROUP BY NOME 
ORDER BY MAIOR_VALOR DESC;

-- CONSULTA GERAL


SELECT * FROM CARGO;
SELECT * FROM PESSOA_CARGO;
SELECT * FROM PESSOA;
SELECT * FROM AGENDAMENTO_PASTORAL;
SELECT * FROM PESSOA_CARGO;
SELECT * FROM DIZIMO;